version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: gymtracker_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/processed:/app/processed

  frontend:
    build:
      context: ./frontend
    container_name: gymtracker_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000